title = "Google Playstore App review Sentiment Classifier"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[training-parameters]
model = "bert-base-uncased"
tokenizer = "bert-base-uncased"
max_length = 160
batch_size = 16
epochs = 50